"""Machine-readable travel equivalence reason codes."""

from enum import Enum


class ReasonCode(str, Enum):
    PASSENGER_MIX_MISMATCH = "PASSENGER_MIX_MISMATCH"
    TRIP_TYPE_MISMATCH = "TRIP_TYPE_MISMATCH"
    SEGMENT_COUNT_MISMATCH = "SEGMENT_COUNT_MISMATCH"
    FLIGHT_NUMBER_MISMATCH = "FLIGHT_NUMBER_MISMATCH"
    MARKETING_CARRIER_MISMATCH = "MARKETING_CARRIER_MISMATCH"
    OPERATING_CARRIER_MISMATCH = "OPERATING_CARRIER_MISMATCH"
    AIRPORT_MISMATCH = "AIRPORT_MISMATCH"
    DATE_MISMATCH = "DATE_MISMATCH"
    CABIN_MISMATCH = "CABIN_MISMATCH"
    BAGGAGE_UNKNOWN = "BAGGAGE_UNKNOWN"
    BAGGAGE_NOT_INCLUDED = "BAGGAGE_NOT_INCLUDED"
    FARE_RESTRICTION_MISMATCH = "FARE_RESTRICTION_MISMATCH"
    REFUNDABILITY_MISMATCH = "REFUNDABILITY_MISMATCH"
    CHANGEABILITY_MISMATCH = "CHANGEABILITY_MISMATCH"
    SELF_TRANSFER = "SELF_TRANSFER"
    SEPARATE_TICKET = "SEPARATE_TICKET"
    PROPERTY_ID_MISMATCH = "PROPERTY_ID_MISMATCH"
    PROPERTY_AMBIGUOUS = "PROPERTY_AMBIGUOUS"
    ROOM_FAMILY_MISMATCH = "ROOM_FAMILY_MISMATCH"
    BED_TYPE_MISMATCH = "BED_TYPE_MISMATCH"
    MEAL_PLAN_MISMATCH = "MEAL_PLAN_MISMATCH"
    CANCELLATION_MISMATCH = "CANCELLATION_MISMATCH"
    PAYMENT_TIMING_MISMATCH = "PAYMENT_TIMING_MISMATCH"
    OCCUPANCY_MISMATCH = "OCCUPANCY_MISMATCH"
    MANDATORY_FEE_UNKNOWN = "MANDATORY_FEE_UNKNOWN"
    TOTAL_INCOMPLETE = "TOTAL_INCOMPLETE"
    STALE_OFFER = "STALE_OFFER"
    SUPPLIER_BLOCKED = "SUPPLIER_BLOCKED"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


EquivalenceReasonCode = ReasonCode

